### ISSUE TITLE
Estimated date of code release

### ISSUE THREAD

**Issue by ashawkey** [wyysf-98/SweetDreamer#1]
Congratulations on the great work!
Do you have an estimated date of code and pretrained model release?

**Comment by ARuiChen** [comment]
We are continuing to finetune the high-quality objaverse dataset that we are further filtering to obtain a high generalization and performance model. At the same time, we are also optimizing the performance of the code, and when everything is ready, it will be released soon.

**Comment by wyysf-98** [comment]
Hi, THANKS for your attention. Unfortunately, we cannot guarantee a specific timeline due to data and company-related reasons. However, we **guarantee** that we will release the code and pre-trained models ASAP. Perhaps we provide a simplified version of the pre-trained model and code soon.

In addition, your work on 3D generation using Gaussian Splatting is truly fascinating. We are currently working on porting our work and creating an online demo to improve efficiency. I have sent you a message and let me know if we can do something together for the community :)
